[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
tip_jar = "6fUfky9N9AA7ySNq6c8F38DDuN1ws7t3zNHRoRoRA7te"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
